"""Small, exhaustive checks for the *Python* destination/WT assignment model.

The golden vector was evaluated with the unrefactored objective on 2026-09-26,
before extracting its per-car calculation. It is not generated by the helper
under test. Run: python tests/test_exact_assignment.py
"""
from __future__ import annotations

import itertools
import os
import sys
import unittest
from unittest.mock import patch

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from decision.exact_assignment import (
    DestinationInstance, car_waiting_cost, solve_exact_assignment,
)
from decision.meta.obj_funs import objFunDestination


def mixed_snapshot():
    return dict(n_floors=8, n_cars=2, traffic=(30, 40, 30),
                car_floor=[2, 6], car_state=[1, -1], car_df=[[6], [2]],
                up=[(2, 6), (2, 5), (1, 4), (5, 8)], dn=[(7, 1), (2, 1)])


# Lexicographic product(range(2), repeat=5); six passengers, five calls.
GOLDEN = [
    15.666666666666666, 14.666666666666666, 11.0, 12.666666666666666,
    14.666666666666666, 14.666666666666666, 11.666666666666666, 14.0,
    17.333333333333332, 17.333333333333332, 15.666666666666666, 17.666666666666668,
    16.333333333333332, 17.333333333333332, 17.0, 19.666666666666668,
    12.666666666666666, 13.333333333333334, 8.333333333333334, 9.0,
    13.666666666666666, 16.0, 10.0, 13.0, 17.0, 18.666666666666668,
    13.0, 15.0, 18.0, 21.333333333333332, 15.0, 19.333333333333332,
]


class GoldenObjectiveTests(unittest.TestCase):
    def test_pre_refactor_values(self):
        instance = DestinationInstance(mixed_snapshot(), 2.0, 0.5)
        population = list(itertools.product(range(2), repeat=5))
        np.testing.assert_allclose(instance.costs(population), GOLDEN,
                                   atol=1e-12, rtol=0)
        # The historical objective uses the FIRST car's velocity for all cars.
        instance.cars[1].velocityFps = 3.0
        self.assertEqual(instance.cost([1] * 5), GOLDEN[-1])

    def test_pickup_opening_is_excluded_from_historical_route_costs(self):
        instance = DestinationInstance(mixed_snapshot(), 2.0, 0.5, door_opening_time=1.25)
        population = list(itertools.product(range(2), repeat=5))
        np.testing.assert_allclose(instance.costs(population), GOLDEN,
                                   atol=1e-12, rtol=0)


def one_call_snapshot(cars=1, passengers=3):
    return dict(n_floors=8, n_cars=cars, traffic=(100, 0, 0),
                car_floor=[1] * cars, car_state=[1] * cars,
                car_df=[[] for _ in range(cars)],
                up=[(3, 4 + k % 5) for k in range(passengers)], dn=[])


class ExactAssignmentTests(unittest.TestCase):
    def test_car_specific_pickup_opening_cost_and_fingerprint(self):
        instance = DestinationInstance(one_call_snapshot(2), 7, 1, door_opening_time=5)
        original_fingerprint = instance.fingerprint()
        instance.cars[1].doorOpeningTime = 1
        self.assertNotEqual(instance.fingerprint(), original_fingerprint)
        # Three passengers; travel=2, openings=5 or 1 do not add pickup cost.
        self.assertEqual(car_waiting_cost(0, 0, instance), 0)
        self.assertEqual(car_waiting_cost(0, 1, instance), 6)
        self.assertEqual(car_waiting_cost(1, 1, instance), 6)
        np.testing.assert_array_equal(instance.costs([[0], [1]]), [2, 2])
        result = solve_exact_assignment(instance)
        self.assertEqual((result.status, result.optimum_mean), ("optimal", 2))
        self.assertEqual(instance.cost(result.assignment), 2)
        for invalid in (-1, float("nan"), float("inf")):
            with self.assertRaises(ValueError):
                DestinationInstance(one_call_snapshot(), 7, 1, door_opening_time=invalid)

    def check_exhaustive(self, snapshot):
        instance = DestinationInstance(snapshot, 2.0, 0.5)
        population = list(itertools.product(range(instance.n_cars), repeat=instance.n_calls))
        # Independent full assignment evaluation, NOT a sum from the cost table.
        direct = instance.costs(population)
        table = [[car_waiting_cost(j, m, instance) for m in range(1 << instance.n_calls)]
                 for j in range(instance.n_cars)]
        for row, expected in zip(population, direct):
            masks = [sum(1 << k for k, label in enumerate(row) if label == j)
                     for j in range(instance.n_cars)]
            total = sum(table[j][m] for j, m in enumerate(masks))
            self.assertAlmostEqual(total / instance.n_passengers, expected, delta=1e-9)
        result = solve_exact_assignment(instance)
        self.assertEqual(result.status, "optimal", result)
        self.assertAlmostEqual(result.optimum_mean, min(direct), delta=1e-9)
        self.assertAlmostEqual(instance.cost(result.assignment), result.optimum_mean, delta=1e-9)
        self.assertAlmostEqual(result.optimum_total / instance.n_passengers,
                               result.optimum_mean, delta=1e-9)
        self.assertEqual(len(result.assignment), instance.n_calls)
        self.assertTrue(all(0 <= x < instance.n_cars for x in result.assignment))
        self.assertEqual(solve_exact_assignment(instance).assignment, result.assignment)

    def test_exhaustive_decomposition_dp_and_traceback(self):
        for snapshot in (mixed_snapshot(), one_call_snapshot(1), one_call_snapshot(3),
                         dict(n_floors=10, n_cars=3, traffic=(30, 40, 30),
                              car_floor=[2, 7, 5], car_state=[1, -1, 0],
                              car_df=[[4, 8], [1, 3], []],
                              up=[(1, 9), (4, 8), (4, 6), (7, 10)],
                              dn=[(4, 2), (8, 3), (9, 1)])):
            with self.subTest(snapshot=snapshot):
                self.check_exhaustive(snapshot)

    def test_idle_costs_match_joint_assignment_and_direction_enumeration(self):
        snapshot = dict(n_floors=8, n_cars=2, car_floor=[4, 6], car_state=[0, 0],
                        car_df=[[], []], up=[(5, 6), (7, 8)], dn=[(2, 1)])
        instance = DestinationInstance(snapshot, 2.0, 0.5)
        population = list(itertools.product(range(2), repeat=instance.n_calls))
        # Independent oracle: enumerate the four FIXED direction pairs, then
        # minimize per assignment. Those evaluations do not use the idle branch.
        direction_costs = []
        for directions in itertools.product((1, -1), repeat=2):
            fixed = DestinationInstance(dict(snapshot, car_state=list(directions)), 2.0, 0.5)
            direction_costs.append(fixed.costs(population))
        expected = np.min(direction_costs, axis=0)
        self.assertTrue(np.any(expected < direction_costs[-1] - 1e-9))
        np.testing.assert_allclose(instance.costs(population), expected, atol=1e-9, rtol=0)
        result = solve_exact_assignment(instance)
        self.assertEqual(result.status, "optimal")
        self.assertAlmostEqual(result.optimum_mean, float(expected.min()), delta=1e-9)
        self.assertAlmostEqual(instance.cost(result.assignment), result.optimum_mean, delta=1e-9)
        self.assertEqual([c.state for c in instance.cars], [0, 0])
        self.check_exhaustive(snapshot)

    def test_passengers_not_calls_are_the_denominator_and_no_capacity_limit(self):
        instance = DestinationInstance(one_call_snapshot(), 2.0, 1.0)
        instance.cars[0].capacity = 1
        instance.cars[0].load = 100
        self.assertEqual((instance.n_calls, instance.n_passengers), (1, 3))
        self.assertEqual(car_waiting_cost(0, 0, instance), 0)
        self.assertEqual(car_waiting_cost(0, 1, instance), 6)
        result = solve_exact_assignment(instance)
        self.assertEqual((result.status, result.optimum_total, result.optimum_mean),
                         ("optimal", 6, 2))
        many = DestinationInstance(one_call_snapshot(passengers=80), 2, 1)
        many.cars[0].capacity = 1
        self.assertEqual(solve_exact_assignment(many).optimum_mean, 2)
        instance.cars[0].DF.add(2)
        self.assertEqual(solve_exact_assignment(instance).optimum_mean, 4)

    def test_shared_interfloor_time_and_car_specific_stop_time(self):
        instance = DestinationInstance(mixed_snapshot(), 2, 0.5)
        instance.cars[1].velocityFps = 3
        instance.cars[1].stopOverTime = 2.3
        for row in itertools.product(range(2), repeat=instance.n_calls):
            total = sum(car_waiting_cost(j, sum(1 << k for k, v in enumerate(row) if v == j),
                                        instance) for j in range(2))
            self.assertAlmostEqual(total / instance.n_passengers, instance.cost(row), delta=1e-9)

    def test_ties_and_strict_dp_improvement_not_hit_tolerance(self):
        instance = DestinationInstance(one_call_snapshot(3), 2, 1)
        self.assertEqual(solve_exact_assignment(instance).assignment, (2,))
        instance.cars[0].floor += 1e-11
        result = solve_exact_assignment(instance)
        self.assertEqual(result.assignment, (0,))
        self.assertLess(result.optimum_mean, 2)

    def test_zero_optimum(self):
        instance = DestinationInstance(one_call_snapshot(), 2, 1)
        instance.cars[0].floor = 3
        result = solve_exact_assignment(instance)
        self.assertEqual((result.status, result.optimum_mean), ("optimal", 0))

    def test_invalid_assignments_and_call_passenger_mapping(self):
        i = DestinationInstance(mixed_snapshot(), 2, 1)
        for row in ([0] * 4, [-1] * 5, [2] * 5, [0.2] * 5, [float("nan")] * 5,
                    [True] * 5, [[0] * 5, [0] * 5]):
            with self.subTest(row=row), self.assertRaises(ValueError):
                i.cost(row)
        for labels in ([[0] * 5], [[3] * 5], [[1.5] * 5]):
            with self.assertRaises(ValueError):
                objFunDestination(i.cars, i.hall_calls, i.num_up_calls,
                                  labels, i.n_floors, i.passengers)
        with self.assertRaises(ValueError):
            objFunDestination(i.cars, [8] + i.hall_calls[1:], i.num_up_calls,
                              [[1] * 5], i.n_floors, i.passengers)
        for change in ({"up": [], "dn": []}, {"car_df": []},
                       {"up": [(3, 1)]}, {"dn": [(9, 1)]}):
            s = mixed_snapshot()
            s.update(change)
            with self.assertRaises(ValueError):
                DestinationInstance(s, 2, 1)

    def test_nonfinite_or_negative_cost_is_an_error(self):
        i = DestinationInstance(mixed_snapshot(), 2, 1)
        with patch("decision.exact_assignment.car_waiting_times",
                   return_value=(np.array([-1.0]), np.array([]))):
            self.assertEqual(solve_exact_assignment(i).status, "invalid_input")
        with patch("decision.exact_assignment.car_waiting_times",
                   return_value=(np.array([np.nan]), np.array([]))):
            self.assertEqual(solve_exact_assignment(i).status, "invalid_input")

    def test_limits_and_cancellation_never_return_an_optimum(self):
        i = DestinationInstance(mixed_snapshot(), 2, 1)
        for kwargs, status in ((dict(max_calls=4), "call_limit"),
                               (dict(time_limit_seconds=0), "time_limit"),
                               (dict(should_cancel=lambda: True), "cancelled"),
                               (dict(time_limit_seconds=-1), "invalid_input")):
            result = solve_exact_assignment(i, **kwargs)
            self.assertEqual(result.status, status)
            self.assertIsNone(result.optimum_mean)
            self.assertIsNone(result.assignment)
        for phase in ("costs", "dp"):
            cancelled = [False]
            def progress(stage, *_):
                if stage == phase:
                    cancelled[0] = True
            result = solve_exact_assignment(i, progress=progress,
                                            should_cancel=lambda: cancelled[0])
            self.assertEqual((result.status, result.stage), ("cancelled", phase))
            self.assertIsNone(result.optimum_mean)

    def test_direct_recheck_disagreement_is_not_optimal(self):
        i = DestinationInstance(mixed_snapshot(), 2, 1)
        with patch.object(i, "cost", return_value=12345):
            result = solve_exact_assignment(i)
        self.assertEqual(result.status, "inconsistent")
        self.assertIsNone(result.optimum_mean)

    def test_timeout_during_each_computational_phase(self):
        i = DestinationInstance(mixed_snapshot(), 2, 1)
        for phase in ("costs", "dp"):
            clock = [0.0]
            def progress(stage, *_):
                if stage == phase:
                    clock[0] = 2.0
            with patch("decision.exact_assignment.time.perf_counter", side_effect=lambda: clock[0]):
                result = solve_exact_assignment(i, time_limit_seconds=1, progress=progress)
            self.assertEqual((result.status, result.stage), ("time_limit", phase))
            self.assertIsNone(result.optimum_mean)
            self.assertIsNone(result.assignment)

    def test_interfloor_time_with_noninteger_costs(self):
        i = DestinationInstance(mixed_snapshot(), 1.37, 0.73)
        rows = list(itertools.product(range(i.n_cars), repeat=i.n_calls))
        result = solve_exact_assignment(i)
        self.assertEqual(result.status, "optimal")
        self.assertAlmostEqual(result.optimum_mean, min(i.costs(rows)), delta=1e-9)


if __name__ == "__main__":
    unittest.main()
